# Generated by Django 2.2.3 on 2019-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20190727_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
